version: '3.8'

services:
  web:
    image: ezza1921/codeigniter4-app:latest
    container_name: codeigniter4-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    networks:
      - codeigniter-net
    depends_on:
      - db
    command: >
      sh -c "docker-php-ext-install mysqli pdo pdo_mysql intl && a2enmod rewrite &&
             echo '<Directory /var/www/html>
                  AllowOverride All
                  Require all granted
                  </Directory>' > /etc/apache2/conf-enabled/allowoverride.conf &&
             apache2-foreground"

  db:
    image: mysql:5.7
    container_name: codeigniter4-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: codeigniter4db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - codeigniter-net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: codeigniter4-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - codeigniter-net

networks:
  codeigniter-net:
    driver: bridge

volumes:
  db-data:
